name: hydra_pipe
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.7.5
  - scikit-learn=0.22.2
  - pandas=0.25.1
  - numpy=1.18.1
  - pip=20.0.2
  - pip:
    - hydra-core==0.11.3  
    - omegaconf==1.4.1
    - xgboost==1.0.2
  

